spring:
  datasource:
    url: jdbc:sqlserver://springboot-sql-jpa.database.windows.net:1433;database=springboot-sql-jpa;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: skm
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
  
